version: '3.7'
services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
  webapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 3000:80
  webapplication-tests:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/test-results.xml