version: '3.7'
services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ValueConnection=Server=sql;Database=MyDatabase;User Id=SA;Password=P@ssw0rd1*.;Connection Timeout=2
      - HealthChecks-UI__HealthChecks__0__Uri=http://localhost:3000/hc
    ports:
      - 3000:80
  api-tests:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/test-results.xml
  sql:
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd1*.
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"