  version: '3.7'

  services:
    seq:
      image: datalust/seq:latest
      volumes:
        - ./tmp/seq:/data
      restart: unless-stopped
    webapplication:
      image: webapplication
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./tmp/logs:/logs
    webapplication-tests:
      image: webapplication-tests
      build:
        context: .
        dockerfile: Dockerfile      
        target: test
      volumes:
      - ./tmp/test:/tests